apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stats
  name: stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/thesis2425/platform/stats
          name: stats
          env:
            - name: PORT
              value: "4900"
            - name: SERVER_SECRET
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: SERVER_SECRET
          ports:
            - containerPort: 4900
              hostPort: 4900
              protocol: TCP
          resources:
            limits:
              memory: "500M"
      restartPolicy: Always
